#!/bin/bash
# Supabase Authentication Setup Guide
# Run these commands or configure manually in Supabase Dashboard

echo "=== Supabase Authentication Setup ==="
echo ""
echo "1. Go to Authentication > Settings in your Supabase Dashboard"
echo ""
echo "2. Configure the following settings:"
echo ""
echo "   📧 EMAIL SETTINGS:"
echo "   - Enable email confirmations: NO (for development)"
echo "   - Enable email change confirmations: NO (for development)"
echo "   - Enable secure email change: NO (for development)"
echo ""
echo "   🔗 SITE URL:"
echo "   - Site URL: http://localhost:3000"
echo "   - Additional redirect URLs: http://localhost:3000/**"
echo ""
echo "   🔑 JWT SETTINGS:"
echo "   - JWT expiry: 3600 seconds (1 hour)"
echo ""
echo "   📱 AUTH PROVIDERS:"
echo "   - Email: ENABLED"
echo "   - Password requirements:"
echo "     * Minimum length: 6 characters"
echo "     * Require lowercase: NO"
echo "     * Require uppercase: NO"
echo "     * Require numbers: NO"
echo "     * Require special characters: NO"
echo ""
echo "3. For production, update these settings:"
echo "   - Enable email confirmations"
echo "   - Set proper site URLs"
echo "   - Configure email templates"
echo ""
echo "4. Optional: Configure additional providers (Google, GitHub, etc.)"
echo ""
echo "=== Email Templates (Optional) ==="
echo "Go to Authentication > Email Templates to customize:"
echo "- Confirm signup"
echo "- Magic link"
echo "- Change email address"
echo "- Reset password"
